name: build

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: build
      run: ./build.sh
    - name: artefact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: |
          dependencies/
        retention-days: 5
