name: build

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./build.sh
    - name: artefact
      uses: actions/upload-artifact@v3
      with:
        name: androidprojectgenerator
        path: androidprojectgenerator.jar
        retention-days: 1
